import type { BlueprintInput } from './types';

/**
 * Archétypes d'idées (section 8).
 *
 * Le moteur ne fabrique pas une idée depuis rien : il classe des archétypes
 * contre un profil. Chacun est un vrai SaaS, constructible avec le parcours de
 * la section 9, vendu à un professionnel qui perd du temps aujourd'hui.
 *
 * Ce fichier est la source du seed. Le front-end, lui, lit la base : ajouter
 * un archétype est une insertion, pas un déploiement.
 */
export interface BlueprintSeed extends BlueprintInput {
  oneLiner: string;
  targetAudience: string;
  problem: string;
  solution: string;
  pricingModel: string;
}

const base = {
  requiresComplexCode: false,
  requiresRegulatedLicense: false,
  requiresPhysicalStock: false,
  requiresTeam: false,
  requiresFace: false,
  requiresOutbound: true,
  monthlyFixedCost: 0,
} as const;

export const BLUEPRINTS: BlueprintSeed[] = [
  {
    ...base,
    slug: 'suivi-seances-kine',
    title: 'Suivi de séances pour cabinets de kiné',
    oneLiner:
      'Le patient reçoit ses exercices sur son téléphone, le kiné voit en un écran qui les a faits.',
    targetAudience: 'Kinésithérapeutes libéraux seuls ou en cabinet de deux à quatre praticiens',
    problem:
      'Entre deux séances, le kiné ne sait pas si le patient a fait ses exercices. Il repose les mêmes questions, réexplique, et perd dix minutes sur trente. Les feuilles d’exercices imprimées finissent au fond d’un sac.',
    solution:
      'Le praticien compose la série d’exercices depuis une bibliothèque, l’envoie par lien. Le patient coche ce qu’il a fait et note sa douleur de 0 à 10. Le praticien ouvre le dossier avant la séance et voit la courbe.',
    pricingModel: 'Abonnement mensuel par praticien',
    monthlyPrice: 29,
    buildComplexity: 3,
    weeksToFirstEuro: 6,
    payerType: 'professional',
    hoursPerWeekMin: 5,
    domains: ['kinesitherapie', 'cabinet-medical'],
    tags: [
      { dimension: 'friction', key: 'suivi-dossier', weight: 1.5 },
      { dimension: 'friction', key: 'compte-rendu', weight: 1 },
      { dimension: 'friction', key: 'notes-eleves', weight: 1 },
      { dimension: 'interest', key: 'sante', weight: 1 },
      { dimension: 'skill', key: 'enseignement', weight: 1 },
      { dimension: 'skill', key: 'organisation', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'planning-restaurant',
    title: 'Planning d’équipe pour petits restaurants',
    oneLiner:
      'Le patron fait le planning de la semaine en dix minutes, l’équipe le reçoit et déclare ses indisponibilités.',
    targetAudience: 'Restaurants indépendants de trois à quinze salariés',
    problem:
      'Le planning se fait le dimanche soir sur un tableur ou une feuille scotchée en cuisine. Une indisponibilité arrive par SMS et se perd. Quand quelqu’un manque, le patron appelle un par un.',
    solution:
      'Chaque salarié pose ses indisponibilités depuis son téléphone. Le patron glisse les créneaux, l’outil signale les trous et les dépassements d’heures. Le planning publié part par SMS. Un remplacement se propose à toute l’équipe d’un bouton.',
    pricingModel: 'Abonnement mensuel par établissement',
    monthlyPrice: 39,
    buildComplexity: 3,
    weeksToFirstEuro: 5,
    payerType: 'business',
    hoursPerWeekMin: 8,
    domains: ['restauration', 'boulangerie'],
    tags: [
      { dimension: 'friction', key: 'planning', weight: 2 },
      { dimension: 'friction', key: 'pointage-heures', weight: 1.5 },
      { dimension: 'friction', key: 'tableur', weight: 1 },
      { dimension: 'interest', key: 'cuisine', weight: 1 },
      { dimension: 'skill', key: 'organisation', weight: 1 },
      { dimension: 'skill', key: 'relation-client', weight: 0.5 },
    ],
  },
  {
    ...base,
    slug: 'suivi-livraisons-transporteur',
    title: 'Suivi de livraisons pour transporteurs indépendants',
    oneLiner:
      'Le chauffeur valide chaque livraison en deux touches, le client reçoit la preuve sans qu’on l’appelle.',
    targetAudience: 'Transporteurs indépendants et petites flottes de un à dix véhicules',
    problem:
      'La preuve de livraison est une photo dans le téléphone du chauffeur. Le donneur d’ordre appelle pour savoir où en est un colis. Le soir, le patron recopie la tournée sur un tableur pour facturer.',
    solution:
      'La tournée du jour s’affiche sur le téléphone du chauffeur. Il valide, photographie, fait signer. Le client suit un lien public. En fin de journée, la tournée devient une ligne de facturation exportable.',
    pricingModel: 'Abonnement mensuel par véhicule',
    monthlyPrice: 25,
    buildComplexity: 3,
    weeksToFirstEuro: 6,
    payerType: 'business',
    hoursPerWeekMin: 8,
    domains: ['transport-livraison', 'entrepot-logistique'],
    tags: [
      { dimension: 'friction', key: 'tournees', weight: 2 },
      { dimension: 'friction', key: 'suivi-dossier', weight: 1.5 },
      { dimension: 'friction', key: 'saisie-manuelle', weight: 1 },
      { dimension: 'friction', key: 'photos-chantier', weight: 1 },
      { dimension: 'skill', key: 'organisation', weight: 1 },
      { dimension: 'skill', key: 'analyse-chiffres', weight: 0.5 },
    ],
  },
  {
    ...base,
    slug: 'rappels-rdv-cabinet',
    title: 'Rappels de rendez-vous pour cabinets paramédicaux',
    oneLiner: 'Un SMS de confirmation la veille, et la case vide se repropose toute seule.',
    targetAudience: 'Orthophonistes, podologues, ostéopathes, psychologues en libéral',
    problem:
      'Un rendez-vous manqué, c’est une heure perdue et personne pour la prendre. Le praticien envoie ses rappels à la main, ou pas du tout.',
    solution:
      'Le praticien importe son agenda. La veille, chaque patient reçoit un message auquel il répond oui ou non. Un désistement propose le créneau aux patients en attente, par ordre d’inscription.',
    pricingModel: 'Abonnement mensuel, SMS inclus jusqu’à un volume',
    monthlyPrice: 19,
    buildComplexity: 3,
    weeksToFirstEuro: 5,
    payerType: 'professional',
    hoursPerWeekMin: 5,
    monthlyFixedCost: 20,
    domains: ['cabinet-medical', 'kinesitherapie', 'coiffure-beaute'],
    tags: [
      { dimension: 'friction', key: 'no-show', weight: 2 },
      { dimension: 'friction', key: 'rendez-vous', weight: 1.5 },
      { dimension: 'interest', key: 'sante', weight: 0.5 },
      { dimension: 'skill', key: 'relation-client', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'commandes-fournisseurs-resto',
    title: 'Commandes fournisseurs pour restaurants',
    oneLiner: 'Les commandes du lendemain partent en un écran, et le prix au kilo cesse de dériver.',
    targetAudience: 'Chefs et gérants de restaurants indépendants',
    problem:
      'Les commandes partent par SMS, par WhatsApp, parfois au téléphone à 6 h du matin. Personne ne sait ce qu’on a payé le même produit le mois dernier.',
    solution:
      'Les produits habituels sont listés par fournisseur. Le chef coche les quantités, l’outil envoie la commande au bon format. Chaque livraison enregistre le prix, et une courbe montre les dérives.',
    pricingModel: 'Abonnement mensuel par établissement',
    monthlyPrice: 35,
    buildComplexity: 3,
    weeksToFirstEuro: 7,
    payerType: 'business',
    hoursPerWeekMin: 8,
    domains: ['restauration', 'boulangerie', 'commerce-detail'],
    tags: [
      { dimension: 'friction', key: 'commandes-fournisseurs', weight: 2 },
      { dimension: 'friction', key: 'stock', weight: 1.5 },
      { dimension: 'friction', key: 'inventaire', weight: 1 },
      { dimension: 'interest', key: 'cuisine', weight: 1 },
      { dimension: 'skill', key: 'negociation', weight: 0.5 },
      { dimension: 'skill', key: 'analyse-chiffres', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'devis-photo-chantier',
    title: 'Devis et photos de chantier pour artisans',
    oneLiner: 'Le devis se fait sur place, depuis les photos, et part avant de remonter dans le camion.',
    targetAudience: 'Artisans du bâtiment seuls ou avec un ou deux compagnons',
    problem:
      'Le devis se fait le soir, fatigué, de mémoire. Les photos du chantier sont mélangées aux photos de famille. Un client sur trois relance avant de recevoir quoi que ce soit.',
    solution:
      'Sur le chantier, l’artisan photographie, dicte, pioche dans ses lignes habituelles. Le devis se génère en PDF et part par mail depuis le téléphone. Chaque chantier garde ses photos avec sa date.',
    pricingModel: 'Abonnement mensuel par artisan',
    monthlyPrice: 29,
    buildComplexity: 3,
    weeksToFirstEuro: 6,
    payerType: 'professional',
    hoursPerWeekMin: 8,
    domains: ['batiment', 'plomberie-elec'],
    tags: [
      { dimension: 'friction', key: 'devis', weight: 2 },
      { dimension: 'friction', key: 'photos-chantier', weight: 1.5 },
      { dimension: 'friction', key: 'relances-clients', weight: 1 },
      { dimension: 'interest', key: 'artisanat', weight: 1 },
      { dimension: 'skill', key: 'bricolage', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'suivi-reparations-garage',
    title: 'Suivi de réparations pour garages',
    oneLiner: 'Le client voit où en est sa voiture sans appeler, et valide le devis d’un bouton.',
    targetAudience: 'Garages indépendants de un à six mécaniciens',
    problem:
      'Le téléphone du garage sonne pour savoir si la voiture est prête. Chaque appel coupe un mécanicien en plein travail. Une réparation supplémentaire attend l’accord du client, parfois deux jours.',
    solution:
      'À l’entrée du véhicule, le garage crée une fiche et envoie un lien. Le client suit les étapes, reçoit les photos de ce qui a été trouvé, accepte ou refuse un supplément en un clic.',
    pricingModel: 'Abonnement mensuel par atelier',
    monthlyPrice: 39,
    buildComplexity: 3,
    weeksToFirstEuro: 7,
    payerType: 'business',
    hoursPerWeekMin: 8,
    domains: ['garage-auto'],
    tags: [
      { dimension: 'friction', key: 'suivi-dossier', weight: 2 },
      { dimension: 'friction', key: 'devis', weight: 1.5 },
      { dimension: 'friction', key: 'relances-clients', weight: 1 },
      { dimension: 'interest', key: 'automobile', weight: 1.5 },
      { dimension: 'skill', key: 'bricolage', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'fiche-client-coiffure',
    title: 'Fiche client pour salons de coiffure et instituts',
    oneLiner: 'La formule exacte de la dernière couleur, retrouvée en trois secondes.',
    targetAudience: 'Salons de coiffure et instituts de beauté de un à huit fauteuils',
    problem:
      'La formule de couleur est notée sur une fiche cartonnée, ou dans la tête de celle qui l’a faite. Quand elle est absente, la cliente repart avec autre chose.',
    solution:
      'Une fiche par cliente : historique, formules, photos avant-après, allergies. Recherche par prénom. Un rappel se déclenche au bout du délai habituel entre deux visites.',
    pricingModel: 'Abonnement mensuel par salon',
    monthlyPrice: 25,
    buildComplexity: 2,
    weeksToFirstEuro: 4,
    payerType: 'business',
    hoursPerWeekMin: 5,
    domains: ['coiffure-beaute'],
    tags: [
      { dimension: 'friction', key: 'suivi-dossier', weight: 2 },
      { dimension: 'friction', key: 'saisie-manuelle', weight: 1 },
      { dimension: 'friction', key: 'rendez-vous', weight: 1 },
      { dimension: 'interest', key: 'mode', weight: 1 },
      { dimension: 'skill', key: 'relation-client', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'planning-menage',
    title: 'Tournées et pointage pour sociétés de nettoyage',
    oneLiner: 'Chaque agent pointe en arrivant, le client voit que c’est fait.',
    targetAudience: 'Sociétés de nettoyage de cinq à trente agents',
    problem:
      'Le pointage se fait sur une feuille laissée sur place. Le client appelle pour dire que personne n’est passé, et personne ne peut prouver le contraire.',
    solution:
      'L’agent scanne un code sur site en arrivant et en partant, coche les prestations faites, photographie si besoin. Le client reçoit un rapport automatique. Les heures sortent en fin de mois.',
    pricingModel: 'Abonnement mensuel par agent',
    monthlyPrice: 9,
    buildComplexity: 3,
    weeksToFirstEuro: 7,
    payerType: 'business',
    hoursPerWeekMin: 8,
    domains: ['menage-proprete'],
    tags: [
      { dimension: 'friction', key: 'pointage-heures', weight: 2 },
      { dimension: 'friction', key: 'planning', weight: 1.5 },
      { dimension: 'friction', key: 'tournees', weight: 1 },
      { dimension: 'skill', key: 'organisation', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'visites-immobilier',
    title: 'Comptes rendus de visite pour agents immobiliers',
    oneLiner: 'Le compte rendu de visite part au vendeur le soir même, sans le rédiger.',
    targetAudience: 'Agents immobiliers indépendants et petites agences',
    problem:
      'Le vendeur veut savoir ce qu’ont dit les visiteurs. L’agent réécrit trois fois la même chose, ou ne le fait pas, et le mandat se tend.',
    solution:
      'À la fin de la visite, l’agent coche les retours sur son téléphone. Le compte rendu se compose et part au vendeur. Un récapitulatif hebdomadaire montre le nombre de visites et les objections récurrentes.',
    pricingModel: 'Abonnement mensuel par agent',
    monthlyPrice: 29,
    buildComplexity: 2,
    weeksToFirstEuro: 5,
    payerType: 'professional',
    hoursPerWeekMin: 5,
    domains: ['immobilier'],
    tags: [
      { dimension: 'friction', key: 'compte-rendu', weight: 2 },
      { dimension: 'friction', key: 'relances-clients', weight: 1.5 },
      { dimension: 'interest', key: 'immobilier', weight: 1.5 },
      { dimension: 'skill', key: 'ecriture', weight: 1 },
      { dimension: 'skill', key: 'vente', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'relance-factures-tpe',
    title: 'Relance de factures impayées pour très petites entreprises',
    oneLiner: 'Les relances partent toutes seules, poliment, jusqu’au paiement.',
    targetAudience: 'Indépendants et TPE qui facturent des entreprises',
    problem:
      'Relancer met mal à l’aise, alors on attend. À soixante jours, l’argent manque en trésorerie et la relance devient un conflit.',
    solution:
      'L’utilisateur dépose ses factures. L’outil suit les échéances et envoie des relances graduées, écrites pour rester correctes. Il voit l’encours total et ce qui est en retard.',
    pricingModel: 'Abonnement mensuel',
    monthlyPrice: 19,
    buildComplexity: 2,
    weeksToFirstEuro: 4,
    payerType: 'professional',
    hoursPerWeekMin: 5,
    domains: ['comptabilite', 'batiment', 'photo-video'],
    tags: [
      { dimension: 'friction', key: 'paiement-retard', weight: 2 },
      { dimension: 'friction', key: 'factures', weight: 1.5 },
      { dimension: 'friction', key: 'relances-clients', weight: 1.5 },
      { dimension: 'interest', key: 'finance', weight: 1 },
      { dimension: 'skill', key: 'ecriture', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'suivi-candidats-interim',
    title: 'Suivi de candidats pour recruteurs de terrain',
    oneLiner: 'Tous les candidats, leur disponibilité et leur dernier échange sur un seul écran.',
    targetAudience: 'Agences d’intérim et cabinets de recrutement de un à dix consultants',
    problem:
      'Les candidats vivent dans une boîte mail, un carnet et trois conversations. On rappelle deux fois la même personne et on oublie celle qui était disponible.',
    solution:
      'Une fiche par candidat avec métier, disponibilité, zone et historique. Une vue « qui est libre la semaine prochaine ». Un message groupé aux profils correspondants à une mission.',
    pricingModel: 'Abonnement mensuel par consultant',
    monthlyPrice: 45,
    buildComplexity: 3,
    weeksToFirstEuro: 7,
    payerType: 'business',
    hoursPerWeekMin: 8,
    domains: ['recrutement-rh'],
    tags: [
      { dimension: 'friction', key: 'recrutement', weight: 2 },
      { dimension: 'friction', key: 'suivi-dossier', weight: 1.5 },
      { dimension: 'friction', key: 'relances-clients', weight: 1 },
      { dimension: 'skill', key: 'relation-client', weight: 1 },
      { dimension: 'skill', key: 'organisation', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'suivi-eleves-soutien',
    title: 'Suivi de progression pour profs particuliers',
    oneLiner: 'Après chaque cours, les parents reçoivent ce qui a été vu et ce qui coince.',
    targetAudience: 'Professeurs particuliers et petites structures de soutien scolaire',
    problem:
      'Les parents paient sans voir ce qui se passe. Le prof refait le point de mémoire, et quand un élève arrête, il n’a rien à montrer.',
    solution:
      'À la fin du cours, le prof coche les notions vues et note l’acquisition. Un compte rendu part aux parents. Une courbe montre la progression sur le trimestre.',
    pricingModel: 'Abonnement mensuel par professeur',
    monthlyPrice: 15,
    buildComplexity: 2,
    weeksToFirstEuro: 4,
    payerType: 'professional',
    hoursPerWeekMin: 5,
    domains: ['education-soutien', 'formation-pro'],
    tags: [
      { dimension: 'friction', key: 'notes-eleves', weight: 2 },
      { dimension: 'friction', key: 'compte-rendu', weight: 1.5 },
      { dimension: 'interest', key: 'education', weight: 1.5 },
      { dimension: 'skill', key: 'enseignement', weight: 1.5 },
      { dimension: 'skill', key: 'ecriture', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'suivi-adherents-club',
    title: 'Suivi d’adhérents pour clubs et associations',
    oneLiner: 'Les licences, les cotisations et les présences au même endroit, sans tableur.',
    targetAudience: 'Clubs sportifs et associations de cinquante à cinq cents adhérents',
    problem:
      'Le trésorier tient un tableur, le secrétaire un autre. On ne sait pas qui a payé, qui a rendu son certificat, qui vient encore.',
    solution:
      'Une fiche par adhérent : cotisation, documents, présences. Des relances automatiques pour les pièces manquantes. Un tableau de bord pour le bureau.',
    pricingModel: 'Abonnement annuel selon le nombre d’adhérents',
    monthlyPrice: 19,
    buildComplexity: 2,
    weeksToFirstEuro: 5,
    payerType: 'business',
    hoursPerWeekMin: 5,
    domains: ['associatif', 'sport-coaching'],
    tags: [
      { dimension: 'friction', key: 'tableur', weight: 2 },
      { dimension: 'friction', key: 'notes-eleves', weight: 1 },
      { dimension: 'friction', key: 'relances-clients', weight: 1 },
      { dimension: 'interest', key: 'sport', weight: 1.5 },
      { dimension: 'skill', key: 'organisation', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'programmes-coach-sportif',
    title: 'Programmes et suivi pour coachs sportifs',
    oneLiner: 'Le client reçoit sa séance, la coche, et le coach voit qui décroche.',
    targetAudience: 'Coachs sportifs indépendants avec dix à soixante clients',
    problem:
      'Les programmes partent en PDF ou en messages. Le coach ne sait pas qui suit vraiment, et perd des clients sans voir venir.',
    solution:
      'Le coach compose un programme depuis sa bibliothèque d’exercices, l’assigne, suit les séances validées et les charges. Une alerte quand quelqu’un n’a rien fait depuis dix jours.',
    pricingModel: 'Abonnement mensuel par coach',
    monthlyPrice: 29,
    buildComplexity: 3,
    weeksToFirstEuro: 5,
    payerType: 'professional',
    hoursPerWeekMin: 5,
    domains: ['sport-coaching'],
    tags: [
      { dimension: 'friction', key: 'notes-eleves', weight: 1.5 },
      { dimension: 'friction', key: 'suivi-dossier', weight: 1.5 },
      { dimension: 'interest', key: 'sport', weight: 2 },
      { dimension: 'interest', key: 'sante', weight: 1 },
      { dimension: 'skill', key: 'enseignement', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'reservations-hebergement',
    title: 'Réservations directes pour petits hébergeurs',
    oneLiner: 'Une page de réservation à soi, pour arrêter de laisser vingt pour cent en commission.',
    targetAudience: 'Chambres d’hôtes, gîtes, petits campings',
    problem:
      'Tout passe par les plateformes, qui prélèvent leur part et gardent le client. Le calendrier se tient à la main et le double-booking arrive.',
    solution:
      'Un calendrier de disponibilités, une page de réservation publique, un acompte par carte, des messages automatiques avant l’arrivée. Synchronisation des calendriers existants pour éviter les doublons.',
    pricingModel: 'Abonnement mensuel par hébergement',
    monthlyPrice: 29,
    buildComplexity: 4,
    weeksToFirstEuro: 8,
    payerType: 'business',
    hoursPerWeekMin: 10,
    domains: ['tourisme-hebergement'],
    tags: [
      { dimension: 'friction', key: 'reservations', weight: 2 },
      { dimension: 'friction', key: 'planning', weight: 1 },
      { dimension: 'interest', key: 'voyage', weight: 1.5 },
      { dimension: 'skill', key: 'relation-client', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'devis-evenementiel',
    title: 'Devis et planning pour prestataires événementiels',
    oneLiner: 'Un devis clair, un planning partagé, et plus personne qui arrive au mauvais endroit.',
    targetAudience: 'DJ, traiteurs, photographes et loueurs de matériel pour événements',
    problem:
      'Chaque événement se négocie par messages. Les horaires changent trois fois. Le jour J, l’équipe n’a pas la même version.',
    solution:
      'Une fiche événement avec devis, acompte, planning heure par heure et liste de matériel. Un lien partagé au client et à l’équipe, toujours à jour.',
    pricingModel: 'Abonnement mensuel par prestataire',
    monthlyPrice: 25,
    buildComplexity: 3,
    weeksToFirstEuro: 6,
    payerType: 'professional',
    hoursPerWeekMin: 8,
    domains: ['evenementiel', 'photo-video'],
    tags: [
      { dimension: 'friction', key: 'devis', weight: 1.5 },
      { dimension: 'friction', key: 'planning', weight: 1.5 },
      { dimension: 'friction', key: 'relances-clients', weight: 1 },
      { dimension: 'interest', key: 'musique', weight: 1 },
      { dimension: 'interest', key: 'image', weight: 1 },
      { dimension: 'skill', key: 'organisation', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'livraison-photos-client',
    title: 'Livraison et validation de photos pour photographes',
    oneLiner: 'Le client choisit ses photos sur une galerie privée, et la sélection revient triée.',
    targetAudience: 'Photographes de mariage, de famille et de produits',
    problem:
      'Les photos partent par lien de transfert, la sélection revient sous forme de liste de numéros dans un mail, parfois faux. Les retouches se font sur les mauvaises images.',
    solution:
      'Une galerie privée par client, favoris et commentaires image par image, export de la sélection, filigrane avant paiement, téléchargement débloqué après.',
    pricingModel: 'Abonnement mensuel selon le stockage',
    monthlyPrice: 19,
    buildComplexity: 3,
    weeksToFirstEuro: 6,
    payerType: 'professional',
    hoursPerWeekMin: 5,
    monthlyFixedCost: 15,
    domains: ['photo-video'],
    tags: [
      { dimension: 'friction', key: 'suivi-dossier', weight: 1 },
      { dimension: 'friction', key: 'relances-clients', weight: 1 },
      { dimension: 'interest', key: 'image', weight: 2 },
      { dimension: 'skill', key: 'photo-video', weight: 2 },
      { dimension: 'skill', key: 'design', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'suivi-troupeau-elevage',
    title: 'Carnet d’élevage pour petites exploitations',
    oneLiner: 'Les traitements, les vêlages et les contrôles notés depuis le champ, pas le soir.',
    targetAudience: 'Éleveurs avec vingt à deux cents animaux',
    problem:
      'Le carnet sanitaire est un cahier dans la voiture. À l’inspection, retrouver une date prend une heure. Les délais d’attente se calculent de tête.',
    solution:
      'Une fiche par animal, saisie en trois touches depuis le téléphone, même sans réseau. Les délais d’attente se calculent seuls et une alerte prévient avant la fin.',
    pricingModel: 'Abonnement mensuel par exploitation',
    monthlyPrice: 25,
    buildComplexity: 4,
    weeksToFirstEuro: 9,
    payerType: 'business',
    hoursPerWeekMin: 10,
    domains: ['agriculture', 'veterinaire'],
    tags: [
      { dimension: 'friction', key: 'saisie-manuelle', weight: 1.5 },
      { dimension: 'friction', key: 'suivi-dossier', weight: 1.5 },
      { dimension: 'interest', key: 'nature', weight: 2 },
      { dimension: 'interest', key: 'animaux', weight: 2 },
      { dimension: 'skill', key: 'organisation', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'stock-atelier-createur',
    title: 'Stock et production pour créateurs et artisans',
    oneLiner: 'Savoir ce qu’on peut encore fabriquer avec ce qui reste sur l’établi.',
    targetAudience: 'Créateurs qui vendent en ligne et sur les marchés',
    problem:
      'Le stock de matières premières se compte à vue. On accepte une commande qu’on ne peut pas honorer, ou on rachète ce qu’on avait déjà.',
    solution:
      'Chaque produit a sa recette de matières. Une vente décrémente automatiquement. L’outil dit combien d’unités sont encore réalisables et ce qu’il faut racheter.',
    pricingModel: 'Abonnement mensuel',
    monthlyPrice: 15,
    buildComplexity: 3,
    weeksToFirstEuro: 7,
    payerType: 'professional',
    hoursPerWeekMin: 5,
    domains: ['artisanat-creation', 'commerce-detail'],
    tags: [
      { dimension: 'friction', key: 'stock', weight: 2 },
      { dimension: 'friction', key: 'inventaire', weight: 1.5 },
      { dimension: 'interest', key: 'artisanat', weight: 2 },
      { dimension: 'skill', key: 'design', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'preparation-commandes-entrepot',
    title: 'Préparation de commandes pour petits entrepôts',
    oneLiner: 'La liste de picking dans le bon ordre des allées, et zéro erreur de colis.',
    targetAudience: 'Petits entrepôts et e-commerçants qui expédient eux-mêmes',
    problem:
      'Les commandes s’impriment dans le désordre. Le préparateur traverse l’entrepôt six fois. Une erreur de colis coûte un retour et un client.',
    solution:
      'Les commandes du jour se regroupent en tournées de picking ordonnées par emplacement. Chaque article se scanne au moment de la mise en colis. Un contrôle final bloque l’expédition si ça ne correspond pas.',
    pricingModel: 'Abonnement mensuel par entrepôt',
    monthlyPrice: 49,
    buildComplexity: 4,
    weeksToFirstEuro: 9,
    payerType: 'business',
    hoursPerWeekMin: 10,
    domains: ['entrepot-logistique', 'commerce-detail'],
    tags: [
      { dimension: 'friction', key: 'inventaire', weight: 1.5 },
      { dimension: 'friction', key: 'stock', weight: 1.5 },
      { dimension: 'friction', key: 'saisie-manuelle', weight: 1 },
      { dimension: 'skill', key: 'organisation', weight: 1.5 },
      { dimension: 'skill', key: 'analyse-chiffres', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'gardes-pharmacie',
    title: 'Planning de gardes et de préparateurs pour pharmacies',
    oneLiner: 'Les gardes, les congés et les renforts sur un seul calendrier que tout le monde voit.',
    targetAudience: 'Pharmacies d’officine de trois à quinze personnes',
    problem:
      'Le planning se négocie de vive voix. Les gardes tombent au mauvais moment. Une absence se découvre le matin même.',
    solution:
      'Un calendrier partagé, des demandes de congés à valider, une rotation de gardes équitable, et un renfort proposé à l’équipe en un message.',
    pricingModel: 'Abonnement mensuel par officine',
    monthlyPrice: 39,
    buildComplexity: 3,
    weeksToFirstEuro: 7,
    payerType: 'business',
    hoursPerWeekMin: 8,
    domains: ['pharmacie', 'cabinet-medical'],
    tags: [
      { dimension: 'friction', key: 'planning', weight: 2 },
      { dimension: 'interest', key: 'sante', weight: 1 },
      { dimension: 'skill', key: 'organisation', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'consultations-veterinaire',
    title: 'Carnet de santé partagé pour cliniques vétérinaires',
    oneLiner: 'Le propriétaire reçoit le compte rendu et les rappels de vaccin sans qu’on y pense.',
    targetAudience: 'Cliniques vétérinaires de un à cinq praticiens',
    problem:
      'Les rappels de vaccin se font par courrier ou pas du tout. Le propriétaire perd l’ordonnance et rappelle. Le compte rendu se redit au téléphone.',
    solution:
      'Une fiche par animal, accessible au propriétaire par lien. Compte rendu et ordonnance déposés après la consultation. Rappels automatiques aux échéances.',
    pricingModel: 'Abonnement mensuel par praticien',
    monthlyPrice: 35,
    buildComplexity: 3,
    weeksToFirstEuro: 7,
    payerType: 'professional',
    hoursPerWeekMin: 8,
    domains: ['veterinaire'],
    tags: [
      { dimension: 'friction', key: 'compte-rendu', weight: 1.5 },
      { dimension: 'friction', key: 'rendez-vous', weight: 1 },
      { dimension: 'friction', key: 'suivi-dossier', weight: 1.5 },
      { dimension: 'interest', key: 'animaux', weight: 2 },
      { dimension: 'interest', key: 'sante', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'bilans-kine-prescripteur',
    title: 'Bilans et comptes rendus pour kinés',
    oneLiner:
      'Le bilan de fin de traitement part au médecin prescripteur en cinq minutes, pas en trois semaines.',
    targetAudience: 'Kinésithérapeutes libéraux qui travaillent sur prescription',
    problem:
      'Le bilan de fin de traitement est obligatoire et personne n’a le temps de le rédiger. Il part en retard, mal formulé, ou pas du tout — et le prescripteur envoie ses patients ailleurs.',
    solution:
      'Le praticien coche les mesures relevées au fil des séances. Le bilan se compose dans le format attendu, avec l’évolution chiffrée, et part au médecin en un bouton. Chaque prescripteur a son historique.',
    pricingModel: 'Abonnement mensuel par praticien',
    monthlyPrice: 19,
    buildComplexity: 2,
    weeksToFirstEuro: 4,
    payerType: 'professional',
    hoursPerWeekMin: 5,
    domains: ['kinesitherapie', 'cabinet-medical'],
    tags: [
      { dimension: 'friction', key: 'compte-rendu', weight: 2 },
      { dimension: 'friction', key: 'saisie-manuelle', weight: 1.5 },
      { dimension: 'interest', key: 'sante', weight: 1.5 },
      { dimension: 'skill', key: 'ecriture', weight: 1 },
      { dimension: 'skill', key: 'enseignement', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'salle-attente-cabinet',
    title: 'File d’attente et annulations pour cabinets',
    oneLiner: 'Une annulation le matin se remplit avant midi, sans passer un seul coup de fil.',
    targetAudience: 'Cabinets paramédicaux de un à six praticiens',
    problem:
      'Quand un patient annule, le créneau reste vide. Le secrétariat appelle une liste au hasard, entre deux patients, et ça ne marche presque jamais.',
    solution:
      'Les patients volontaires s’inscrivent sur une liste d’attente avec leurs créneaux possibles. Une annulation déclenche une proposition ciblée. Le premier qui répond prend la place.',
    pricingModel: 'Abonnement mensuel par cabinet',
    monthlyPrice: 29,
    buildComplexity: 3,
    weeksToFirstEuro: 6,
    payerType: 'professional',
    hoursPerWeekMin: 5,
    domains: ['cabinet-medical', 'kinesitherapie', 'veterinaire'],
    tags: [
      { dimension: 'friction', key: 'no-show', weight: 2 },
      { dimension: 'friction', key: 'rendez-vous', weight: 2 },
      { dimension: 'interest', key: 'sante', weight: 1 },
      { dimension: 'skill', key: 'organisation', weight: 1.5 },
    ],
  },
  {
    ...base,
    slug: 'pourboires-service-resto',
    title: 'Répartition des pourboires et des heures en salle',
    oneLiner: 'La répartition du service se calcule toute seule, et plus personne ne conteste.',
    targetAudience: 'Restaurants et brasseries avec une équipe de salle',
    problem:
      'La répartition des pourboires se fait de tête, en fin de service, et crée des tensions toutes les semaines. Les heures réelles ne correspondent jamais au planning affiché.',
    solution:
      'Chaque service enregistre qui était là et combien de temps. La cagnotte se répartit selon la règle choisie par l’équipe, visible de tous. Chacun voit son cumul du mois.',
    pricingModel: 'Abonnement mensuel par établissement',
    monthlyPrice: 25,
    buildComplexity: 2,
    weeksToFirstEuro: 4,
    payerType: 'business',
    hoursPerWeekMin: 5,
    domains: ['restauration', 'boulangerie'],
    tags: [
      { dimension: 'friction', key: 'pointage-heures', weight: 2 },
      { dimension: 'friction', key: 'saisie-manuelle', weight: 1 },
      { dimension: 'interest', key: 'cuisine', weight: 1 },
      { dimension: 'skill', key: 'relation-client', weight: 1 },
      { dimension: 'skill', key: 'analyse-chiffres', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'reservations-resto',
    title: 'Réservations et rappels pour restaurants',
    oneLiner: 'La table réservée qui ne vient pas coûte cher : un rappel la veille suffit souvent.',
    targetAudience: 'Restaurants indépendants qui prennent des réservations',
    problem:
      'Les réservations se notent sur un cahier. Le soir, deux tables ne viennent pas et personne n’était sur liste d’attente. Le cahier ne dit rien de qui annule tout le temps.',
    solution:
      'Une page de réservation publique, un plan de salle simple, un rappel automatique la veille avec confirmation. Les créneaux libérés se reproposent. Chaque client garde un historique.',
    pricingModel: 'Abonnement mensuel par établissement',
    monthlyPrice: 35,
    buildComplexity: 3,
    weeksToFirstEuro: 6,
    payerType: 'business',
    hoursPerWeekMin: 8,
    domains: ['restauration'],
    tags: [
      { dimension: 'friction', key: 'reservations', weight: 2 },
      { dimension: 'friction', key: 'no-show', weight: 2 },
      { dimension: 'friction', key: 'rendez-vous', weight: 1 },
      { dimension: 'interest', key: 'cuisine', weight: 1.5 },
      { dimension: 'skill', key: 'relation-client', weight: 1.5 },
    ],
  },
  {
    ...base,
    slug: 'entretien-flotte-transport',
    title: 'Entretien et coûts de flotte pour transporteurs',
    oneLiner: 'Chaque véhicule dit lui-même quand il doit passer à la révision, et ce qu’il coûte au kilomètre.',
    targetAudience: 'Transporteurs et artisans avec deux à quinze véhicules',
    problem:
      'Les révisions se ratent, les contrôles techniques se découvrent la veille. Personne ne sait quel véhicule coûte le plus cher, donc on garde celui qui ruine la marge.',
    solution:
      'Une fiche par véhicule : kilométrage, entretiens, carburant, réparations. Les échéances déclenchent une alerte. Un coût au kilomètre par véhicule, comparable d’un mois sur l’autre.',
    pricingModel: 'Abonnement mensuel par véhicule',
    monthlyPrice: 15,
    buildComplexity: 2,
    weeksToFirstEuro: 5,
    payerType: 'business',
    hoursPerWeekMin: 5,
    domains: ['transport-livraison', 'garage-auto'],
    tags: [
      { dimension: 'friction', key: 'saisie-manuelle', weight: 1.5 },
      { dimension: 'friction', key: 'tableur', weight: 1.5 },
      { dimension: 'interest', key: 'automobile', weight: 1.5 },
      { dimension: 'skill', key: 'analyse-chiffres', weight: 1.5 },
      { dimension: 'skill', key: 'tableur', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'affectation-quais-entrepot',
    title: 'Affectation des quais et des créneaux de chargement',
    oneLiner: 'Le chauffeur réserve son créneau de quai, et la file devant l’entrepôt disparaît.',
    targetAudience: 'Entrepôts et plateformes qui reçoivent dix à cent camions par jour',
    problem:
      'Les camions arrivent quand ils veulent. Trois attendent, deux quais sont vides. Le chauffeur perd deux heures, le cariste ne sait pas ce qui arrive.',
    solution:
      'Le transporteur réserve un créneau de quai en ligne. L’entrepôt voit sa journée à l’avance et répartit ses caristes. Un retard se signale et décale la file automatiquement.',
    pricingModel: 'Abonnement mensuel par site',
    monthlyPrice: 49,
    buildComplexity: 3,
    weeksToFirstEuro: 8,
    payerType: 'business',
    hoursPerWeekMin: 8,
    domains: ['entrepot-logistique', 'transport-livraison'],
    tags: [
      { dimension: 'friction', key: 'planning', weight: 2 },
      { dimension: 'friction', key: 'reservations', weight: 1.5 },
      { dimension: 'skill', key: 'organisation', weight: 2 },
      { dimension: 'skill', key: 'analyse-chiffres', weight: 1 },
    ],
  },
  {
    ...base,
    slug: 'notes-frais-tpe',
    title: 'Notes de frais photographiées pour petites équipes',
    oneLiner: 'Le ticket se photographie en sortant du restaurant, et le comptable reçoit tout trié.',
    targetAudience: 'TPE de cinq à cinquante salariés sans logiciel de gestion',
    problem:
      'Les tickets s’accumulent dans une pochette et arrivent chez le comptable en vrac, trois mois plus tard, parfois illisibles.',
    solution:
      'Le salarié photographie, l’outil lit le montant et la date, la dépense part en validation. Export mensuel au format attendu par le cabinet comptable.',
    pricingModel: 'Abonnement mensuel par utilisateur',
    monthlyPrice: 7,
    buildComplexity: 4,
    weeksToFirstEuro: 9,
    payerType: 'business',
    hoursPerWeekMin: 10,
    monthlyFixedCost: 30,
    domains: ['comptabilite'],
    tags: [
      { dimension: 'friction', key: 'saisie-manuelle', weight: 2 },
      { dimension: 'friction', key: 'factures', weight: 1.5 },
      { dimension: 'interest', key: 'finance', weight: 1.5 },
      { dimension: 'skill', key: 'analyse-chiffres', weight: 1.5 },
      { dimension: 'skill', key: 'tableur', weight: 1 },
    ],
  },
];
