import type { Difficulty } from '@prisma/client';

export const SKILLS: Array<{ slug: string; label: string; category: string }> = [
  { slug: 'video_editing', label: 'Montage vidéo', category: 'création' },
  { slug: 'video_shooting', label: 'Tournage', category: 'création' },
  { slug: 'photo', label: 'Photo', category: 'création' },
  { slug: 'design', label: 'Design graphique', category: 'création' },
  { slug: 'copywriting', label: 'Écriture persuasive', category: 'création' },
  { slug: 'writing', label: 'Rédaction', category: 'création' },
  { slug: 'social_media', label: 'Réseaux sociaux', category: 'marketing' },
  { slug: 'ads', label: 'Publicité en ligne', category: 'marketing' },
  { slug: 'seo', label: 'Référencement', category: 'marketing' },
  { slug: 'email_marketing', label: 'E-mailing', category: 'marketing' },
  { slug: 'sales', label: 'Vente', category: 'commerce' },
  { slug: 'negotiation', label: 'Négociation', category: 'commerce' },
  { slug: 'prospecting', label: 'Prospection', category: 'commerce' },
  { slug: 'customer_service', label: 'Relation client', category: 'commerce' },
  { slug: 'coding', label: 'Développement', category: 'technique' },
  { slug: 'no_code', label: 'Outils no-code', category: 'technique' },
  { slug: 'data_analysis', label: 'Analyse de données', category: 'technique' },
  { slug: 'automation', label: 'Automatisation', category: 'technique' },
  { slug: 'project_management', label: 'Organisation de projet', category: 'gestion' },
  { slug: 'accounting', label: 'Gestion et comptabilité', category: 'gestion' },
  { slug: 'teaching', label: 'Transmettre et expliquer', category: 'humain' },
  { slug: 'public_speaking', label: 'Parler en public', category: 'humain' },
  { slug: 'manual_work', label: 'Travail manuel', category: 'terrain' },
  { slug: 'logistics', label: 'Logistique', category: 'terrain' },
];

export const INTERESTS: Array<{ slug: string; label: string }> = [
  { slug: 'fitness', label: 'Sport et fitness' },
  { slug: 'nutrition', label: 'Nutrition' },
  { slug: 'beauty', label: 'Beauté et cosmétique' },
  { slug: 'fashion', label: 'Mode' },
  { slug: 'food', label: 'Cuisine et restauration' },
  { slug: 'travel', label: 'Voyage' },
  { slug: 'gaming', label: 'Jeu vidéo' },
  { slug: 'tech', label: 'Technologie' },
  { slug: 'finance', label: 'Finance et investissement' },
  { slug: 'real_estate', label: 'Immobilier' },
  { slug: 'education', label: 'Éducation' },
  { slug: 'health', label: 'Santé et bien-être' },
  { slug: 'parenting', label: 'Famille et parentalité' },
  { slug: 'pets', label: 'Animaux' },
  { slug: 'home', label: 'Maison et décoration' },
  { slug: 'diy', label: 'Bricolage et artisanat' },
  { slug: 'music', label: 'Musique' },
  { slug: 'art', label: 'Art et illustration' },
  { slug: 'video', label: 'Vidéo et audiovisuel' },
  { slug: 'business', label: 'Entrepreneuriat' },
  { slug: 'marketing', label: 'Marketing' },
  { slug: 'ecology', label: 'Écologie' },
  { slug: 'automotive', label: 'Automobile' },
  { slug: 'sport_business', label: 'Salles de sport et coaching' },
];

export const MILESTONES: Array<{ key: string; label: string; order: number }> = [
  { key: 'first_prospect', label: 'Premier prospect', order: 1 },
  { key: 'first_meeting', label: 'Premier rendez-vous', order: 2 },
  { key: 'first_client', label: 'Premier client', order: 3 },
  { key: 'first_revenue', label: 'Premier revenu', order: 4 },
];

type Tag = { dimension: string; key: string; weight: number };

export interface BusinessSeed {
  slug: string;
  name: string;
  summary: string;
  economicModel: string;
  difficulty: Difficulty;
  minBudget: number;
  maxBudget: number;
  hoursPerWeekMin: number;
  hoursPerWeekMax: number;
  timeToFirstClientDays: number;
  requiresFace?: boolean;
  requiresContent?: boolean;
  requiresSelling?: boolean;
  requiresLocalPresence?: boolean;
  scoringWeights: Record<string, number>;
  tags: Tag[];
}

/**
 * Référentiel des business models (section 6.2). Ajouter une entrée ici est une
 * insertion en base : aucun écran, aucun composant ne connaît ces slugs.
 */
export const BUSINESS_MODELS: BusinessSeed[] = [
  {
    slug: 'agence-ugc',
    name: 'Agence UGC',
    summary:
      'Tu produis des vidéos authentiques pour des marques, filmées par toi, utilisées dans leurs publicités. Pas d’audience à construire : la marque paie la vidéo, pas ta notoriété.',
    economicModel: 'Prestation à la vidéo ou au pack mensuel, facturée à la marque.',
    difficulty: 'easy',
    minBudget: 0,
    maxBudget: 500,
    hoursPerWeekMin: 8,
    hoursPerWeekMax: 25,
    timeToFirstClientDays: 30,
    requiresFace: true,
    requiresContent: true,
    scoringWeights: {
      skills: 1.1, interests: 1.1, behavior: 1.5, personality: 0.7, budget: 0.6,
      time: 1, risk: 0.5, marketDemand: 1.2, monetizationSpeed: 1.4, acquisition: 1.2, constraints: 0.8,
    },
    tags: [
      { dimension: 'skills', key: 'video_shooting', weight: 2 },
      { dimension: 'skills', key: 'video_editing', weight: 1.5 },
      { dimension: 'skills', key: 'copywriting', weight: 1 },
      { dimension: 'skills', key: 'social_media', weight: 1 },
      { dimension: 'interests', key: 'video', weight: 1.5 },
      { dimension: 'interests', key: 'fitness', weight: 1 },
      { dimension: 'interests', key: 'beauty', weight: 1 },
      { dimension: 'interests', key: 'food', weight: 1 },
      { dimension: 'interests', key: 'fashion', weight: 1 },
      { dimension: 'behavior', key: 'content_production', weight: 2 },
      { dimension: 'behavior', key: 'on_camera', weight: 2 },
      { dimension: 'behavior', key: 'outreach', weight: 1.5 },
      { dimension: 'personality', key: 'solo', weight: 1 },
      { dimension: 'personality', key: 'creative', weight: 1.5 },
      { dimension: 'market', key: 'demand', weight: 0.85 },
      { dimension: 'niche', key: 'fitness', weight: 1 },
      { dimension: 'niche', key: 'beauty', weight: 1 },
      { dimension: 'acquisition', key: 'outbound', weight: 2 },
      { dimension: 'acquisition', key: 'content', weight: 1 },
    ],
  },
  {
    slug: 'freelance-video',
    name: 'Freelance vidéo',
    summary:
      'Tu montes et produis des vidéos pour des entreprises et des créateurs. Compétence facturée à la journée ou au projet.',
    economicModel: 'Facturation au projet ou en abonnement de montage mensuel.',
    difficulty: 'easy',
    minBudget: 0,
    maxBudget: 800,
    hoursPerWeekMin: 10,
    hoursPerWeekMax: 40,
    timeToFirstClientDays: 25,
    scoringWeights: {
      skills: 1.8, interests: 0.8, behavior: 1.2, personality: 0.7, budget: 0.6,
      time: 1.1, risk: 0.5, marketDemand: 1.1, monetizationSpeed: 1.3, acquisition: 1.1, constraints: 0.8,
    },
    tags: [
      { dimension: 'skills', key: 'video_editing', weight: 2.5 },
      { dimension: 'skills', key: 'video_shooting', weight: 1 },
      { dimension: 'skills', key: 'design', weight: 0.8 },
      { dimension: 'interests', key: 'video', weight: 2 },
      { dimension: 'behavior', key: 'creation', weight: 2 },
      { dimension: 'behavior', key: 'outreach', weight: 1.2 },
      { dimension: 'personality', key: 'solo', weight: 1.5 },
      { dimension: 'market', key: 'demand', weight: 0.8 },
      { dimension: 'acquisition', key: 'outbound', weight: 1.5 },
      { dimension: 'acquisition', key: 'referral', weight: 1 },
    ],
  },
  {
    slug: 'agence-contenu',
    name: 'Agence de contenu',
    summary:
      'Tu prends en charge la production de contenu d’une entreprise : articles, vidéos courtes, visuels. Récurrent par nature.',
    economicModel: 'Abonnement mensuel par client, volume de livrables défini.',
    difficulty: 'medium',
    minBudget: 100,
    maxBudget: 2000,
    hoursPerWeekMin: 12,
    hoursPerWeekMax: 40,
    timeToFirstClientDays: 45,
    requiresSelling: true,
    scoringWeights: {
      skills: 1.2, interests: 0.9, behavior: 1.4, personality: 0.9, budget: 0.9,
      time: 1.2, risk: 0.8, marketDemand: 1.1, monetizationSpeed: 1, acquisition: 1.3, constraints: 0.9,
    },
    tags: [
      { dimension: 'skills', key: 'copywriting', weight: 2 },
      { dimension: 'skills', key: 'social_media', weight: 1.5 },
      { dimension: 'skills', key: 'project_management', weight: 1.5 },
      { dimension: 'interests', key: 'marketing', weight: 1.5 },
      { dimension: 'behavior', key: 'content_production', weight: 1.5 },
      { dimension: 'behavior', key: 'outreach', weight: 2 },
      { dimension: 'behavior', key: 'selling', weight: 1.5 },
      { dimension: 'personality', key: 'team', weight: 1 },
      { dimension: 'market', key: 'demand', weight: 0.8 },
      { dimension: 'acquisition', key: 'outbound', weight: 2 },
    ],
  },
  {
    slug: 'lead-generation',
    name: 'Lead generation',
    summary:
      'Tu fournis des contacts qualifiés à des entreprises qui vendent cher : artisans, agences immobilières, cabinets. Tu es payé au résultat.',
    economicModel: 'Paiement au lead ou forfait mensuel avec objectif de volume.',
    difficulty: 'medium',
    minBudget: 200,
    maxBudget: 3000,
    hoursPerWeekMin: 10,
    hoursPerWeekMax: 35,
    timeToFirstClientDays: 40,
    requiresSelling: true,
    scoringWeights: {
      skills: 1.2, interests: 0.6, behavior: 1.4, personality: 1, budget: 1.2,
      time: 1, risk: 1, marketDemand: 1.2, monetizationSpeed: 1.1, acquisition: 1.5, constraints: 0.9,
    },
    tags: [
      { dimension: 'skills', key: 'ads', weight: 2 },
      { dimension: 'skills', key: 'sales', weight: 1.5 },
      { dimension: 'skills', key: 'data_analysis', weight: 1.2 },
      { dimension: 'interests', key: 'marketing', weight: 1.5 },
      { dimension: 'interests', key: 'real_estate', weight: 1 },
      { dimension: 'behavior', key: 'analysis', weight: 1.5 },
      { dimension: 'behavior', key: 'outreach', weight: 2 },
      { dimension: 'behavior', key: 'selling', weight: 1.5 },
      { dimension: 'personality', key: 'analytical', weight: 1.5 },
      { dimension: 'market', key: 'demand', weight: 0.75 },
      { dimension: 'acquisition', key: 'paid', weight: 2 },
      { dimension: 'acquisition', key: 'outbound', weight: 1.5 },
    ],
  },
  {
    slug: 'gestion-reseaux-sociaux',
    name: 'Gestion de réseaux sociaux',
    summary:
      'Tu gères les comptes sociaux d’entreprises locales ou de marques : calendrier, publications, réponses, croissance.',
    economicModel: 'Abonnement mensuel par compte géré.',
    difficulty: 'easy',
    minBudget: 0,
    maxBudget: 400,
    hoursPerWeekMin: 8,
    hoursPerWeekMax: 30,
    timeToFirstClientDays: 30,
    scoringWeights: {
      skills: 1.2, interests: 1, behavior: 1.3, personality: 0.8, budget: 0.6,
      time: 1.1, risk: 0.5, marketDemand: 1.1, monetizationSpeed: 1.3, acquisition: 1.2, constraints: 0.9,
    },
    tags: [
      { dimension: 'skills', key: 'social_media', weight: 2.5 },
      { dimension: 'skills', key: 'copywriting', weight: 1.5 },
      { dimension: 'skills', key: 'design', weight: 1 },
      { dimension: 'interests', key: 'marketing', weight: 1.5 },
      { dimension: 'behavior', key: 'content_production', weight: 2 },
      { dimension: 'behavior', key: 'repetition', weight: 1.5 },
      { dimension: 'behavior', key: 'outreach', weight: 1.2 },
      { dimension: 'personality', key: 'structure', weight: 1 },
      { dimension: 'market', key: 'demand', weight: 0.8 },
      { dimension: 'acquisition', key: 'outbound', weight: 1.5 },
      { dimension: 'acquisition', key: 'local', weight: 1 },
    ],
  },
  {
    slug: 'service-local',
    name: 'Service local',
    summary:
      'Tu rends un service sur le terrain près de chez toi : nettoyage, jardinage, montage, dépannage, aide à domicile.',
    economicModel: 'Facturation à la prestation, souvent récurrente.',
    difficulty: 'easy',
    minBudget: 50,
    maxBudget: 1500,
    hoursPerWeekMin: 6,
    hoursPerWeekMax: 40,
    timeToFirstClientDays: 14,
    requiresLocalPresence: true,
    requiresSelling: true,
    scoringWeights: {
      skills: 1, interests: 0.6, behavior: 1.2, personality: 0.8, budget: 0.9,
      time: 1.2, risk: 0.5, marketDemand: 1.3, monetizationSpeed: 1.6, acquisition: 1.3, constraints: 1.2,
    },
    tags: [
      { dimension: 'skills', key: 'manual_work', weight: 2 },
      { dimension: 'skills', key: 'customer_service', weight: 1.5 },
      { dimension: 'interests', key: 'home', weight: 1 },
      { dimension: 'interests', key: 'diy', weight: 1 },
      { dimension: 'behavior', key: 'repetition', weight: 1.5 },
      { dimension: 'behavior', key: 'outreach', weight: 1.5 },
      { dimension: 'behavior', key: 'selling', weight: 1.2 },
      { dimension: 'personality', key: 'structure', weight: 1 },
      { dimension: 'market', key: 'demand', weight: 0.9 },
      { dimension: 'acquisition', key: 'local', weight: 2.5 },
      { dimension: 'acquisition', key: 'referral', weight: 1.5 },
    ],
  },
  {
    slug: 'consulting',
    name: 'Consulting',
    summary:
      'Tu vends ton expertise sur un problème précis : audit, plan d’action, accompagnement. Peu de production, beaucoup de discernement.',
    economicModel: 'Honoraires à la journée, au forfait ou en accompagnement mensuel.',
    difficulty: 'medium',
    minBudget: 0,
    maxBudget: 1000,
    hoursPerWeekMin: 8,
    hoursPerWeekMax: 35,
    timeToFirstClientDays: 45,
    requiresSelling: true,
    scoringWeights: {
      skills: 1.6, interests: 0.8, behavior: 1.3, personality: 1, budget: 0.6,
      time: 0.9, risk: 0.8, marketDemand: 1, monetizationSpeed: 1.1, acquisition: 1.3, constraints: 0.9,
    },
    tags: [
      { dimension: 'skills', key: 'teaching', weight: 2 },
      { dimension: 'skills', key: 'project_management', weight: 1.5 },
      { dimension: 'skills', key: 'data_analysis', weight: 1.2 },
      { dimension: 'skills', key: 'public_speaking', weight: 1.2 },
      { dimension: 'interests', key: 'business', weight: 1.5 },
      { dimension: 'behavior', key: 'analysis', weight: 2 },
      { dimension: 'behavior', key: 'outreach', weight: 1.5 },
      { dimension: 'behavior', key: 'selling', weight: 1.5 },
      { dimension: 'personality', key: 'analytical', weight: 1.5 },
      { dimension: 'market', key: 'demand', weight: 0.7 },
      { dimension: 'acquisition', key: 'outbound', weight: 2 },
      { dimension: 'acquisition', key: 'referral', weight: 1.5 },
    ],
  },
  {
    slug: 'micro-saas',
    name: 'Micro-SaaS',
    summary:
      'Tu construis un petit logiciel qui résout un problème étroit, vendu en abonnement. Long à démarrer, récurrent ensuite.',
    economicModel: 'Abonnement mensuel, faible prix unitaire, volume.',
    difficulty: 'hard',
    minBudget: 100,
    maxBudget: 3000,
    hoursPerWeekMin: 15,
    hoursPerWeekMax: 40,
    timeToFirstClientDays: 90,
    scoringWeights: {
      skills: 1.8, interests: 0.8, behavior: 1.1, personality: 1, budget: 0.9,
      time: 1.3, risk: 1.4, marketDemand: 1, monetizationSpeed: 0.8, acquisition: 1.1, constraints: 0.9,
    },
    tags: [
      { dimension: 'skills', key: 'coding', weight: 2.5 },
      { dimension: 'skills', key: 'no_code', weight: 1.5 },
      { dimension: 'skills', key: 'automation', weight: 1.2 },
      { dimension: 'interests', key: 'tech', weight: 2 },
      { dimension: 'behavior', key: 'creation', weight: 2 },
      { dimension: 'behavior', key: 'analysis', weight: 1.5 },
      { dimension: 'personality', key: 'solo', weight: 1.5 },
      { dimension: 'personality', key: 'analytical', weight: 1.5 },
      { dimension: 'market', key: 'demand', weight: 0.6 },
      { dimension: 'acquisition', key: 'content', weight: 1.5 },
      { dimension: 'acquisition', key: 'outbound', weight: 1.2 },
    ],
  },
  {
    slug: 'e-commerce',
    name: 'E-commerce',
    summary:
      'Tu vends des produits physiques en ligne. Demande du capital de départ, de la logistique et de la publicité.',
    economicModel: 'Marge sur produit, volume acquis par la publicité.',
    difficulty: 'hard',
    minBudget: 1000,
    maxBudget: 10000,
    hoursPerWeekMin: 15,
    hoursPerWeekMax: 45,
    timeToFirstClientDays: 60,
    scoringWeights: {
      skills: 1.2, interests: 1, behavior: 1.1, personality: 0.8, budget: 2,
      time: 1.2, risk: 1.5, marketDemand: 1.2, monetizationSpeed: 0.9, acquisition: 1.5, constraints: 1,
    },
    tags: [
      { dimension: 'skills', key: 'ads', weight: 2 },
      { dimension: 'skills', key: 'logistics', weight: 1.5 },
      { dimension: 'skills', key: 'design', weight: 1 },
      { dimension: 'interests', key: 'fashion', weight: 1 },
      { dimension: 'interests', key: 'home', weight: 1 },
      { dimension: 'behavior', key: 'analysis', weight: 1.5 },
      { dimension: 'behavior', key: 'repetition', weight: 1.2 },
      { dimension: 'personality', key: 'analytical', weight: 1.2 },
      { dimension: 'market', key: 'demand', weight: 0.8 },
      { dimension: 'acquisition', key: 'paid', weight: 2.5 },
    ],
  },
  {
    slug: 'abonnement',
    name: 'Offre par abonnement',
    summary:
      'Tu vends un service récurrent à prix fixe : box, maintenance, accompagnement. Revenu prévisible, exigence de constance.',
    economicModel: 'Abonnement mensuel, rétention au cœur du modèle.',
    difficulty: 'medium',
    minBudget: 200,
    maxBudget: 4000,
    hoursPerWeekMin: 10,
    hoursPerWeekMax: 35,
    timeToFirstClientDays: 50,
    requiresSelling: true,
    scoringWeights: {
      skills: 1.1, interests: 0.9, behavior: 1.2, personality: 1, budget: 1.2,
      time: 1.1, risk: 1, marketDemand: 1.1, monetizationSpeed: 1, acquisition: 1.2, constraints: 1,
    },
    tags: [
      { dimension: 'skills', key: 'customer_service', weight: 2 },
      { dimension: 'skills', key: 'project_management', weight: 1.5 },
      { dimension: 'interests', key: 'business', weight: 1 },
      { dimension: 'behavior', key: 'repetition', weight: 2 },
      { dimension: 'behavior', key: 'selling', weight: 1.5 },
      { dimension: 'personality', key: 'structure', weight: 1.5 },
      { dimension: 'market', key: 'demand', weight: 0.7 },
      { dimension: 'acquisition', key: 'outbound', weight: 1.5 },
      { dimension: 'acquisition', key: 'content', weight: 1 },
    ],
  },
  {
    slug: 'newsletter',
    name: 'Newsletter',
    summary:
      'Tu écris régulièrement pour une audience ciblée, monétisée par le sponsoring ou un abonnement payant. Lent, puis durable.',
    economicModel: 'Sponsoring à l’envoi ou abonnement payant des lecteurs.',
    difficulty: 'medium',
    minBudget: 0,
    maxBudget: 600,
    hoursPerWeekMin: 6,
    hoursPerWeekMax: 20,
    timeToFirstClientDays: 90,
    requiresContent: true,
    scoringWeights: {
      skills: 1.4, interests: 1.4, behavior: 1.2, personality: 0.9, budget: 0.5,
      time: 0.9, risk: 1, marketDemand: 0.9, monetizationSpeed: 0.7, acquisition: 1.2, constraints: 0.8,
    },
    tags: [
      { dimension: 'skills', key: 'writing', weight: 2.5 },
      { dimension: 'skills', key: 'email_marketing', weight: 1.5 },
      { dimension: 'skills', key: 'copywriting', weight: 1.5 },
      { dimension: 'interests', key: 'finance', weight: 1 },
      { dimension: 'interests', key: 'tech', weight: 1 },
      { dimension: 'interests', key: 'marketing', weight: 1 },
      { dimension: 'behavior', key: 'content_production', weight: 2 },
      { dimension: 'behavior', key: 'repetition', weight: 1.5 },
      { dimension: 'personality', key: 'solo', weight: 1.5 },
      { dimension: 'market', key: 'demand', weight: 0.55 },
      { dimension: 'acquisition', key: 'content', weight: 2.5 },
    ],
  },
  {
    slug: 'produit-numerique',
    name: 'Produit numérique',
    summary:
      'Tu conçois une ressource vendue en ligne : modèle, outil, pack. Effort concentré au départ, vente répétable ensuite.',
    economicModel: 'Vente unitaire, marge quasi totale, volume nécessaire.',
    difficulty: 'medium',
    minBudget: 0,
    maxBudget: 800,
    hoursPerWeekMin: 8,
    hoursPerWeekMax: 25,
    timeToFirstClientDays: 60,
    requiresContent: true,
    scoringWeights: {
      skills: 1.3, interests: 1.2, behavior: 1.1, personality: 0.9, budget: 0.6,
      time: 1, risk: 1, marketDemand: 1, monetizationSpeed: 0.9, acquisition: 1.3, constraints: 0.8,
    },
    tags: [
      { dimension: 'skills', key: 'design', weight: 1.5 },
      { dimension: 'skills', key: 'writing', weight: 1.5 },
      { dimension: 'skills', key: 'teaching', weight: 1.5 },
      { dimension: 'skills', key: 'no_code', weight: 1 },
      { dimension: 'interests', key: 'education', weight: 1.5 },
      { dimension: 'behavior', key: 'creation', weight: 2 },
      { dimension: 'behavior', key: 'content_production', weight: 1.5 },
      { dimension: 'personality', key: 'solo', weight: 1.5 },
      { dimension: 'personality', key: 'creative', weight: 1.5 },
      { dimension: 'market', key: 'demand', weight: 0.65 },
      { dimension: 'acquisition', key: 'content', weight: 2 },
    ],
  },
  {
    slug: 'affiliation',
    name: 'Affiliation',
    summary:
      'Tu recommandes des produits que tu ne fabriques pas et touches une commission. Dépend entièrement d’un flux d’audience.',
    economicModel: 'Commission sur vente, aucun stock, aucun service après-vente.',
    difficulty: 'medium',
    minBudget: 0,
    maxBudget: 1500,
    hoursPerWeekMin: 6,
    hoursPerWeekMax: 25,
    timeToFirstClientDays: 75,
    requiresContent: true,
    scoringWeights: {
      skills: 1.2, interests: 1.3, behavior: 1.2, personality: 0.8, budget: 0.8,
      time: 0.9, risk: 1.1, marketDemand: 1, monetizationSpeed: 0.8, acquisition: 1.5, constraints: 0.8,
    },
    tags: [
      { dimension: 'skills', key: 'seo', weight: 2 },
      { dimension: 'skills', key: 'copywriting', weight: 1.5 },
      { dimension: 'skills', key: 'social_media', weight: 1.5 },
      { dimension: 'interests', key: 'tech', weight: 1 },
      { dimension: 'interests', key: 'finance', weight: 1 },
      { dimension: 'behavior', key: 'content_production', weight: 2 },
      { dimension: 'behavior', key: 'analysis', weight: 1.2 },
      { dimension: 'personality', key: 'solo', weight: 1.5 },
      { dimension: 'market', key: 'demand', weight: 0.6 },
      { dimension: 'acquisition', key: 'content', weight: 2.5 },
    ],
  },
  {
    slug: 'marketplace',
    name: 'Place de marché',
    summary:
      'Tu mets en relation une offre et une demande et prends une commission. Le problème n’est pas technique, il est d’amorçage.',
    economicModel: 'Commission sur transaction, croissance des deux côtés en parallèle.',
    difficulty: 'hard',
    minBudget: 500,
    maxBudget: 8000,
    hoursPerWeekMin: 18,
    hoursPerWeekMax: 45,
    timeToFirstClientDays: 120,
    requiresSelling: true,
    scoringWeights: {
      skills: 1.4, interests: 0.8, behavior: 1.3, personality: 1, budget: 1.3,
      time: 1.4, risk: 1.6, marketDemand: 1.1, monetizationSpeed: 0.6, acquisition: 1.4, constraints: 1,
    },
    tags: [
      { dimension: 'skills', key: 'no_code', weight: 1.8 },
      { dimension: 'skills', key: 'sales', weight: 1.8 },
      { dimension: 'skills', key: 'project_management', weight: 1.5 },
      { dimension: 'interests', key: 'business', weight: 1.5 },
      { dimension: 'behavior', key: 'outreach', weight: 2 },
      { dimension: 'behavior', key: 'analysis', weight: 1.5 },
      { dimension: 'personality', key: 'team', weight: 1.2 },
      { dimension: 'market', key: 'demand', weight: 0.5 },
      { dimension: 'acquisition', key: 'outbound', weight: 2 },
      { dimension: 'acquisition', key: 'paid', weight: 1.2 },
    ],
  },
  {
    slug: 'creation-contenu',
    name: 'Création de contenu',
    summary:
      'Tu construis une audience sur un sujet, monétisée par le sponsoring, tes propres offres ou les plateformes. Le plus lent, le plus composé.',
    economicModel: 'Sponsoring, produits propres, revenus de plateforme.',
    difficulty: 'hard',
    minBudget: 0,
    maxBudget: 2000,
    hoursPerWeekMin: 10,
    hoursPerWeekMax: 40,
    timeToFirstClientDays: 120,
    requiresFace: true,
    requiresContent: true,
    scoringWeights: {
      skills: 1.2, interests: 1.5, behavior: 1.4, personality: 0.9, budget: 0.6,
      time: 1.2, risk: 1.4, marketDemand: 0.9, monetizationSpeed: 0.6, acquisition: 1.2, constraints: 0.9,
    },
    tags: [
      { dimension: 'skills', key: 'video_editing', weight: 2 },
      { dimension: 'skills', key: 'public_speaking', weight: 1.5 },
      { dimension: 'skills', key: 'copywriting', weight: 1.2 },
      { dimension: 'interests', key: 'video', weight: 1.5 },
      { dimension: 'interests', key: 'gaming', weight: 1 },
      { dimension: 'interests', key: 'music', weight: 1 },
      { dimension: 'behavior', key: 'content_production', weight: 2.5 },
      { dimension: 'behavior', key: 'on_camera', weight: 2.5 },
      { dimension: 'behavior', key: 'repetition', weight: 1.5 },
      { dimension: 'personality', key: 'creative', weight: 2 },
      { dimension: 'market', key: 'demand', weight: 0.5 },
      { dimension: 'acquisition', key: 'content', weight: 3 },
    ],
  },
];

type PlanKey = 'free' | 'pro' | 'illimite';

export const FEATURE_FLAGS: Array<{ key: string; label: string; plans: PlanKey[] }> = [
  { key: 'diagnostic.full', label: 'Diagnostic complet', plans: ['free', 'pro', 'illimite'] },
  { key: 'recommendation.view', label: 'Recommandation', plans: ['free', 'pro', 'illimite'] },
  { key: 'journey.preview', label: 'Aperçu du parcours', plans: ['free', 'pro', 'illimite'] },
  { key: 'adventure.public', label: 'Aventure publique', plans: ['free', 'pro', 'illimite'] },
  { key: 'journey.full', label: 'Parcours complet', plans: ['pro', 'illimite'] },
  { key: 'assistant.contextual', label: 'Assistance contextuelle', plans: ['pro', 'illimite'] },
  { key: 'notifications.reminders', label: 'Rappels et notifications', plans: ['pro', 'illimite'] },
  { key: 'history.full', label: 'Historique complet', plans: ['pro', 'illimite'] },
  { key: 'journey.multiple', label: 'Plusieurs activités en parallèle', plans: ['illimite'] },
  { key: 'journey.variants', label: 'Toutes les variantes de parcours', plans: ['illimite'] },
  { key: 'assistant.unlimited', label: 'Assistance sans limite', plans: ['illimite'] },
];
